# Day 3 Assignment Solutions

### Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [1]:
import numpy as np

In [2]:
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Questions 2:
Accept two lists of 5 elements each from the user. \n
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
ls1 = list()
ls2 = list()

for i in range(5):
    a = int(input())
    ls1.append(a)

for i in range(5):
    a = int(input())
    ls2.append(a)
    
arr = np.array([ls1, ls2])

print(arr)
print(np.sort(arr))

6
5
3
9
7
4
8
1
2
0
[[6 5 3 9 7]
 [4 8 1 2 0]]
[[3 5 6 7 9]
 [0 1 2 4 8]]


### Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.


In [5]:
arr = np.array([[6,6,8,1,2,5,4,8], [6,8,9,1,3,4,4,2], [9,8,6,5,6,5,1,7]])

print(arr)
print()
print(arr.shape)
print()
print(arr.size)

[[6 6 8 1 2 5 4 8]
 [6 8 9 1 3 4 4 2]
 [9 8 6 5 6 5 1 7]]

(3, 8)

24


### Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print()
b = np.reshape(a,(3,3))
print(b)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[9,8,7],[7,6,5]])
vs = np.vstack((a,b))
hs = np.hstack((a,b))
print(vs)
print()
print(hs)

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [7 6 5]]

[[1 2 3 9 8 7]
 [4 5 6 7 6 5]]


### Questions 6:
How to get unique items and counts of unique items?

In [8]:
x = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(x, return_counts=True)

print(np.asarray((unique, counts)).T)

[[ 1  5]
 [ 2  3]
 [ 5  1]
 [25  1]]
